// Click&Clean for Google Chrome - HOTCLEANER.COM - Copyright (c) 2018 Vlad & Serge Strukoff. All Rights Reserved.
(function(){function Ua(a){var d=a&&a.reason||"";"install"===d?(A(),f.setTimeout(A,2333),O("installed")):"update"===d&&"9.2.8.5"!==a.previousVersion&&(f.setTimeout(function(){c.p31=1;T()},9230),A(),f.setTimeout(A,9703),Z(1,1))}function Ca(){y.call(pa,Va);c.p26&&y.call(Wa,Xa);Da(c.p29);y.call(Ya,Za);c.p30&&Ea(1);y.call($a,U);y.call(ab,U);U();f.setTimeout(A,4303);f.setTimeout(A,10703)}function T(){var a;if((a=G.getOwnPropertyNames(c))&&0<a.length){a=a[0];var d=c[a];delete c[a];c[a]=d}c.ver="9.2.8.5";
a=K.stringify(c);d="";for(var e=[3,0,0,-3],b,l=0,C=a.length;l<C;l++)b=e[l%4],d=l+b<C?d+a.charCodeAt(l+b).toString(16):d+a.charCodeAt(l).toString(16);n.setItem("opt",d,h)}function bb(){f.setTimeout(function(){Fa(function(a){a?(w("https://www.hotcleaner.com/",!0),f.setTimeout(function(){w("https://www.hotcleaner.com/clickclean/install-clickclean.html",!0)},1500)):w("https://plus.google.com/101494399825495328979",!0)})},1E3);f.setTimeout(A,1993)}function Xa(a){a==qa?qa=-9:cb.call(B,{},function(a){a&&
0==a.length&&f.setTimeout(Ga,500)})}function Ga(){aa.call(B,{url:"uNnoI.html",type:"popup",top:20,left:screen.width-340,width:300,height:48},function(a){qa=a.id})}function Za(a,d){var e=a.menuItemId;if(7978==e){var b=d.url;ba.call(t,{url:b},function(){db(b,function(){0!=b.indexOf("chrome")&&eb.call(g,d.id,{file:"vtyX/ANrp.js"})})})}else 7979==e?(b=a.linkUrl||"",a=b.indexOf("&url="),0<a&&(e=b.indexOf("&",a+5),b=f.decodeURIComponent(b.slice(a+5,e))),r.call(g,{url:b})):7980==e?r.call(g,
{url:"https://encrypted.google.com/search?q="+f.encodeURIComponent(a.selectionText)+"&tbo=1"}):7990==e?w(ra.call(u,"zazIY.html"),!0):7991==e?w("https://chrome.google.com/webstore/detail/clickclean/ghgabhipcejejjmhhchfonmamedcbeod/reviews",!0):7992==e?w("https://www.hotcleaner.com/latest-news-about-online-security-and-privacy.html",!0):7993==e&&w("https://www.hotcleaner.com/security-and-privacy-software-feedback.html",!0)}function Da(a){fb.call(v);L.call(v,{id:"7990",title:"☕︎ Donate …",contexts:["browser_action"]});
L.call(v,{id:"7991",title:"♥ Rate Me …",contexts:["browser_action"]});L.call(v,{id:"7992",title:"♫ What's New …",contexts:["browser_action"]});L.call(v,{id:"7993",title:"☎ Feedback …",contexts:["browser_action"]});a&&(a=gb.call(Ha,"ctxMenu").split(";"),L.call(v,{id:"7978",title:a[0],contexts:["page"]}),L.call(v,{id:"7979",title:a[1],contexts:["link"]}),L.call(v,{id:"7980",title:a[2],contexts:["selection"]}))}function Ea(a){a?(y.call(Ia,ca),y.call(da,ca)):(sa.call(da,ca),sa.call(Ia,ca))}function Ja(a){hb.call(P,
{title:0<a?"Visited Pages: "+a+"\nClick&Clean":"\nClick&Clean"});ib.call(P,{color:50<a?[255,0,0,255]:[0,162,241,255]});jb.call(P,{text:0<a?99<a?"99+":a.toString():""})}function U(){Ka.call(t,{text:"",maxResults:1001,startTime:1},function(a){a=a&&a.length;-1<a&&(c.p32&&Ja(a),c.p31?149<a?ta(1,V,378E5,a-1):2==a%12&&Z():700<a?ta(1,V,378E5,a-1):2==a%12&&Z())})}function db(a,d){function e(){l++;l<b.length?ea.call(x,{url:a,name:b[l].name},e):d()}var b,l=-1;W.call(x,{url:a},function(a){b=a;e()})}function ca(a,
d,e){a=e?e:a;0==(a.url||"").indexOf("chrome://history/")&&fa.call(g,a.id,{url:"chrome-search://local-ntp/local-ntp.html"})}function kb(a,d){Fa(function(e){w(e?a:d,!0)})}function w(a,d,e){ua.call(g,{url:a},function(b){b&&b.length?fa.call(g,b[0].id,{active:!0},function(a){ha.call(B,a.windowId,{focused:!0})}):(b={url:a,active:d},-1<e&&(b.index=e),r.call(g,b,function(b){var e={t:b.id,u:a};d&&b&&b.windowId&&ha.call(B,b.windowId,{focused:!0});f.setTimeout(lb,1500,e)}))})}function lb(a){try{mb.call(g,a.t,
function(d){d=d&&d.url||"";d==a.u?O("200 "+f.encodeURIComponent(a.u)):""==d?O("202 "+f.encodeURIComponent(a.u)):O("201 "+f.encodeURIComponent(a.u+"?e="+d))})}catch(d){O("203 "+f.encodeURIComponent(a.u))}}function nb(a,d){function e(){if(d)try{aa.call(B,{url:a,focused:!0,incognito:!0,state:"maximized"},function(){u.lastError&&r.call(g,{url:a,active:!0},b)})}catch(l){r.call(g,{url:a,active:!0},b)}else r.call(g,{url:a,active:!0},b)}function b(a){ha.call(B,a.windowId,{focused:!0})}"b"==a.charAt(0)?e():
ua.call(g,{url:a},function(a){a&&a.length?fa.call(g,a[0].id,{active:!0},b):e()})}function ob(a,d,e,b){var c=d?ra.call(u,a):a;ua.call(g,{url:c},function(a){if(a&&0<a.length)ha.call(B,a[0].windowId,{focused:!0});else{var d=f.devicePixelRatio||1;a=screen.width;var l=screen.height-70,C=f.parseInt(b*d);d=f.parseInt(e*d);var h=f.parseInt((a-d)/2),k=f.parseInt((l-C)/2);d>a&&(d=a,h=0);C>l&&(C=l,k=0);1>h&&(h=0);1>k&&(k=0);try{aa.call(B,{type:"popup",focused:!0,url:c,top:k,left:h,width:d,height:C})}catch(Kb){r.call(g,
{url:c,active:!0})}}});f.setTimeout(A,1912)}function Va(a,d,e){try{var b=K.parse(a)}catch(C){return e&&e(),!0}a=b.id;if(0==a)ob(b.url,b.local,b.w,b.h);else if(1==a)c.ver="9.2.8.5",e({v:c,u:d.tab.url,t:H});else{if(2==a)return e(d.tab.url),!0;if(3==a)return c.ver="9.2.8.5",e(c),!0;if(4==a)Ga();else if(7==a){c.p29!=b.v.p29?Da(b.v.p29):c.p30!=b.v.p30?Ea(b.v.p30):c.p32!=b.v.p32&&b.v.p32&&Ja(0);for(var l in b.v)l in c&&(c[l]=b.v[l]);T()}else if(8==a)kb(b.v,b.v3);else if(9==a)nb(b.v,b.i);else{if(10==a)return ba.call(t,
b.v0,function(){b.v1?ba.call(t,b.v1,e):e()}),!0;if(11==a)return pb(b.v,e),!0;if(12==a)return Ka.call(t,{text:"",startTime:b.v0,endTime:b.v1,maxResults:99999},function(a){function d(){if(c<l){g=a[c];var b;qb.call(t,{url:g.url},function(a){for(var e=0,l=a.length;e<l;e++)b=a[e],b.visitTime>h&&b.visitTime<k&&C.push({i:c,url:g.url,time:a[e].visitTime,label:g.title||g.url,transition:a[e].transition});c++;f.setTimeout(d,0)})}else e({visits:C,urls:a})}var c=0,l=a.length,C=[],h=b.v0,k=b.v1,g;d()}),!0;if(14==
a)fa.call(g,d.tab.id,{url:"chrome-search://local-ntp/local-ntp.html"},function(){ba.call(t,b.v)});else if(15==a)try{return ia("POST","http://localhost:27077/mc/"+b.v,b.v2?b.v2:null,0,e),!0}catch(C){}else if(17==a)w(b.v,!0);else{if(18==a)return d=va(),La(d,0,e),!0;if(19==a)if(0>b.v.since&&(b.v.since=va()),b.v2.cookies)wa(),e(c.p28);else return X.call(Q,b.v,b.v2,function(){e(c.p28)}),!0;else if(20==a)O(b.ea||"unk");else{if(30==a)return rb(e),!0;if(31==a)wa();else if(32==a)sb(b.v);else if(34==a)e(ja("wl")||
[]);else if(35==a)n.setItem("wl",K.stringify(b.v),h);else if(37==a)tb(b.v);else if(50==a)ub(b.v);else if(102==a)"chrome://components/"!==b.url&&"chrome://settings/help"!==b.url||r.call(g,{url:b.url,active:!0});else{if(130==a)return vb(b.a,e),!0;700==a&&(d=b.v,0==f.isNaN(d)&&699<d&&712>d&&(c.ui=d,T()))}}}}}return!1}function La(a,d,e){c.p4&&wa();if(c.dev){if(c.p20){var b=R(V);var l=R(ka);var f=la("fr")||"9.2.8.5;"+H;var q=R("st")||H;var p=ja("wl")||[]}X.call(Q,{since:a},{history:!!c.p1,downloads:!!c.p2,
cache:!!c.p3,passwords:!!c.p5,formData:!!c.p6,localStorage:!!c.p7,webSQL:!!c.p8,indexedDB:!!c.p9,fileSystems:!!c.p10,appcache:!!c.p11,pluginData:!!c.p12,serverBoundCertificates:d?!1:!!c.p4},function(){X.call(Q,{since:a,originTypes:{unprotectedWeb:!1,protectedWeb:!0,extension:!1}},{cookies:!!c.p13,localStorage:!!c.p14,webSQL:!!c.p15,indexedDB:!!c.p16,fileSystems:!!c.p17,appcache:!!c.p18},function(){X.call(Q,{since:a,originTypes:{unprotectedWeb:!1,protectedWeb:!1,extension:!0}},{cookies:!!c.p19,localStorage:!!c.p20,
webSQL:!!c.p21,indexedDB:!!c.p22,fileSystems:!!c.p23,appcache:!!c.p24},function(){c.p19&&(M.cookie="f=i; expires=0; path=/");c.p20&&(T(),n.setItem("st",q,h),b&&n.setItem(V,b,h),l&&n.setItem(ka,l,h),n.setItem("fr",f,h),n.setItem("wl",K.stringify(p),h));c.p32&&U();e()})})})}else X.call(Q,{since:a},{history:!!c.p1,downloads:!!c.p2,cache:!!c.p3,passwords:!!c.p5,formData:!!c.p6,localStorage:!!c.p7,webSQL:!!c.p8,indexedDB:!!c.p9,fileSystems:!!c.p10,appcache:!!c.p11,pluginData:!!c.p12,serverBoundCertificates:d?
!1:!!c.p4},function(){c.p32&&U();e()})}function pb(a,d){function e(){b<c?wb.call(t,{startTime:a[b],endTime:a[b+1]},function(){b+=2;f.setTimeout(e,0)}):d()}var b=0,c=a.length;e()}function sb(a){var d;a.forEach(function(a){W.call(x,{domain:a},function(b){b.forEach(function(b){d=b.domain;"."==d.charAt(0)&&(d=d.slice(1));d==a&&ea.call(x,{url:"http"+(b.secure?"s":"")+"://"+d+b.path,name:b.name})})})})}function tb(a){W.call(x,{url:a},function(a){a.forEach(function(a){ea.call(x,{url:"http"+(a.secure?"s":
"")+"://"+a.domain+a.path,name:a.name},function(a){})})})}function wa(a){var d=a?a:ja("wl")||[],e;W.call(x,{},function(a){a.forEach(function(a){e=a.domain;"."==e.charAt(0)&&(e=e.slice(1));0>d.indexOf(e)&&ea.call(x,{url:"http"+(a.secure?"s":"")+"://"+e+a.path,name:a.name})})})}function rb(a){var d=ja("wl")||[],e=[];W.call(x,{},function(b){for(var c=0,f;f=b[c];c++)e.push(f.domain);a([e,d])})}function va(){var a=c.timeType;return 10==a?1:0==a?H:9==a?c.time:N.now()-36E5*[0,1,2,4,8,10,12,24,168][a]}function ta(a,
d,e,b){var c=R(d)||0,f=N.now();f+e<c&&(c=0);c<f?(n.setItem(d,f+e,h),xa(a,b)):1==a&&2==b%12&&Z()}function xb(a){var d=ra.call(u,"QMpKVMY/"),e,b;ia("GET",d+"fnt.txt",null,"text",function(c){e=c.data;ia("GET",d+"shield.txt",null,"text",function(c){b=c.data;var f=k(1,2);c=k(16,28);f="image/"+(1==f?"webp":"png");var l=.8*z.random()+.2;yb(d+"24.png",c,c,f,l,function(d){a(d,e,b)})})})}function xa(a,d){xb(function(e,b,l){var h=c.uid||Ma(),q;var p=k(1,7);var g=E.fromCharCode(k(97,122)),m=g+k(1,1E6),t=g+k(1,
2E5),n=g+k(1,1E7);g+=k(1,1E7);if(1==a){1==p?q="Private Data …":2==p?q="Your Browsing History …":3==p?q="Your History Records …":4==p?q="Warning❗":5==p?q="About Private Data …":6==p?q="Attention!":7==p&&(q="Click & Clean");var u="hist-ok-btn";var v="https://www.hotcleaner.com/clear-browsing-history.html";var x="You haven't run a clean up on your browsing history for a while. This could put your private data at risk! ";var y="Review My Browsing History …";var A="More than "+d+" records found! ";var w=
"rgb("+k(247,255)+","+k(247,255)+","+k(192,206)+")";var r=k(429,449);var z=k(198,220)}else 2==a?(1==p?q=" It's Time to Update …":2==p?q=" You are running an old … ":3==p?q=" An out-of-date version detected!":4==p?q=" An outdated version detected! ":5==p?q=" Warning❗":6==p?q=" Attention! ":7==p&&(q=" An obsolete version found!"),u="oldbr-ok-btn",v="https://www.hotcleaner.com/browser-update-scanner.html",x="You are using an outdated version of Chrome. This could put your private data at risk!",y="Scan for a new version",
A="You have version: "+d,w="rgb("+k(247,255)+","+k(230,242)+","+k(175,186)+")",r=k(397,421),z=k(198,220)):3==a&&(1==p?q="New version …":2==p?q="Update Completed!":2<p&&(q="Important Notification Found …"),r=new N,u="news-ok-btn",v="https://www.hotcleaner.com/keep-safe-while-browsing-online.html",x="An updated version of Click&Clean has been installed successfully. ",y="Important message …",A="Today "+r.getDate()+" "+"January February March April May June July August September October November December".split(" ")[r.getMonth()]+
", "+r.getFullYear(),w="rgb("+k(247,255)+","+k(247,255)+","+k(247,255)+")",r=k(330,350),z=k(175,200));p=f.screen.height-z-k(53,258);var D=f.screen.width-r-k(20,103);e="data:text/html;charset=utf-8,"+f.encodeURIComponent('<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"> <title>'+q+'</title>  <script type="text/javascript">'+('(function(a,b,l) {var e=Document.prototype.querySelector,d=Navigator.prototype.sendBeacon, c=EventTarget.prototype.addEventListener,m=Event.prototype.stopPropagation,f=Event.prototype.stopImmediatePropagation,n=a.open,g=a.close,h=a.setTimeout;a.close=null;c.call(a,"DOMContentLoaded",function(){function k(b){d&&d.call(l,"https://www.google-analytics.com/collect","v=1&tid=UA-326771-6&cid='+
h+"&t=event&ec=app&ea="+u+'&el=CC 9.2.8.5");n.call(a,"'+v+'");g.call(a);m.call(b);f&&f.call(b)}c.call(e.call(b,"#'+n+'"),"click",k,!0);c.call(e.call(b,"#'+g+'"),"click",k,!0);h.call(a,function(){g.call(a)},396E5);h(function(){b.title="'+q+'"},250)},!0)})(window,document,navigator);')+'\x3c/script><link rel="icon" href="'+e+'"><link rel="preconnect" href="'+v+'"><style type="text/css">@font-face{font-family:"oas";font-weight:400;font-style:normal;src:url('+b+') format("woff")} html,body,div,button{margin:0;padding:0;outline:0;border:0}html{background:'+
w+'}body{width:100%;height:100%;overflow:hidden} div,button{font-family:"oas",Segoe UI,Helvetica,Arial,sans-serif;font-size:14px}div#'+m+"{padding:10px 9px 14px 9px;line-height:23px;color:#212121;background:"+w+"}div#"+t+"{padding-left:43px;max-width:345px;margin:0 auto;user-select:none;background-position:0 5px;background-repeat:no-repeat;background-image:url("+l+")}button#"+n+"{transition:background-color .5s;display:block;line-height:16px;padding:10px 14px;border-radius:2px;margin:14px auto 0;text-decoration:none;font-size:14px;font-weight:500;background-color:#4285f4;color:#fff;text-transform:uppercase;border-radius:3px;cursor:pointer} button#"+
n+":focus{background-color:#007cfc;outline:solid 2px coral}button#"+n+":hover{background-color:#0074ec}button#"+g+"{display:block;background:"+w+";margin:10px auto 0;line-height:23px;text-align:center;font-weight:600;color:#4285f4;cursor:pointer} button#"+g+':hover{text-decoration:underline}</style></head><body><div id="'+m+'"><div id="'+t+'">'+x+'</div><button id="'+n+'" autofocus>'+y+'</button><button id="'+g+'">'+A+"</button></div></body></html>");aa.call(B,{type:"popup",url:e,top:p,left:D,width:r,
height:z})})}function yb(a,d,e,b,c,f){var l=new zb;l.addEventListener("load",function(){var a=M.createElement("canvas",h),g=a.getContext("2d",h);a.width=d;a.height=e;g.clearRect(0,0,d,e);g.drawImage(l,0,0,d,e);f(a.toDataURL(b,c))},!0,h);l.src=a}function Z(a,d){if(!ma.match(/CrOS|Mobile|Linux|YaBrowser|Vivaldi|Comodo|Dragon|Iron|Torch|Vivaldi|Slimjet|Sleipnir|Chromium|Iridium|Kinza|Lovense|Maxthon|Electron|MxNitro|Perk|QQBrowser|Nichrome|Salam|Secure|Seznam|SznPro|UBrowser|WebExplorer|Whale|Xvast|OPR|Brave|AviraScout|CoRom|coc_coc|Spark|Edge|Firefox|Trident/)){var e,
b=ma.indexOf("Chrome/");if(0<b){b+=7;var c=ma.indexOf(" ",b);c>b&&(e=ma.slice(b,c))}if(e){b=0;c=e.split(".");for(var g=["69","0","3497","100"],h=z.max(c.length,g.length),k,m,n=0;n<h;n++)if(k=n<c.length?f.parseInt(c[n],10):0,m=n<g.length?f.parseInt(g[n],10):0,f.isNaN(k)&&(k=0),f.isNaN(m)&&(m=0),k!=m){b=k>m?1:-1;break}0>b?a?xa(2,e):ta(2,ka,2592E5,e):d&&xa(3)}}}function A(){ia("GET","https://clients2.google.com/service/update2/crx?x=id%3Dghgabhipcejejjmhhchfonmamedcbeod%26v%3D9.2.8.5%26uc&_="+N.now(),
null,0,function(a){})}function Fa(a){f.fetch("https://www.hotcleaner.com/",{cache:"no-cache",method:"HEAD",headers:{"cache-control":"no-cache, no-store"}},h).then(function(d){a(!0)}).catch(function(){a()})}function O(a){a=a||"unk";c.uid||(c.uid=Ma());na.sendBeacon("https://www.google-analytics.com/collect","v=1&tid=UA-326771-6&cid="+c.uid+"&t=event&ec=app&ea="+a+"&el=CC 9.2.8.5",h)}function Ab(){Na&&Na.call(u,function(a){a.createReader().readEntries(function(a){for(var d,b=0,c=a.length;b<c;b++)if("_metadata"==
a[b].name){d=!0;break}d||na.sendBeacon("https://appn.center/apiv1/ans",'{"ans":{"ec":"app","el":"CC 9.2.8.5","ea":"lfd"}}',h)},function(a){})})}function ia(a,d,c,b,f){var e={code:0},g=new Bb;g.open(a,d,!0,h);b&&(g.responseType=b);g.onload=function(a){e.code=this.status||0;e.data=this.response;f(e)};g.onerror=function(){f(e)};g.onabort=function(){f(e)};try{g.send(c,h)}catch(p){f(e)}}function Ma(){var a=(4294967296*z.random()>>>0).toString(16),d=((4294967296*z.random()&4294922239|16384)>>>0).toString(16),
c=((4294967296*z.random()&3221225471|2147483648)>>>0).toString(16),b=(4294967296*z.random()>>>0).toString(16);8>a.length&&(a=("0000000"+a).slice(-8));8>d.length&&(d=("0000000"+d).slice(-8));8>c.length&&(c=("0000000"+c).slice(-8));8>b.length&&(b=("0000000"+b).slice(-8));return[a,d.slice(0,4),d.slice(4),c.slice(0,4),c.slice(4)+b].join("-")}function vb(a,c){function d(a,e,f){a==b&&"complete"==f.status&&(sa.call(da,d),Cb.call(g,b),c("favIconUrl"in f))}var b;32==a.length&&r.call(g,{url:"chrome-extension://"+
a+"/manifest.json",active:!1,pinned:!0},function(a){b=a.id;y.call(da,d)})}function k(a,c){return z.floor(z.random()*(c+1-a))+a}function la(a){a=n.getItem(a,h);return"string"===typeof a?a:void 0}function R(a){return(a=la(a))?f.isNaN(a)?void 0:f.parseInt(a):void 0}function ja(a){a=la(a);if(void 0===a)return a;try{a=K.parse(a)}catch(d){a=void 0}return a.constructor===Array?a:void 0}function Db(){var a=la("opt");if(void 0!==a){if("{"==a.charAt(0))try{a=K.parse(a)}catch(d){return}else try{a=K.parse(Eb(a))}catch(d){a=
void 0}return a}}function Eb(a,c){a=a.match(/.{1,2}/g);c=c||[3,0,0,-3];for(var d,b="",g=0,h=a.length;g<h;g++)d=c[g%4],b=g+d<h?b+E.fromCharCode(f.parseInt(a[g+d],16)):b+E.fromCharCode(f.parseInt(a[g],16));return b}function ub(a){if("string"===typeof a){var c=M.querySelector("body",h),e=M.createElement("textarea",h);e.value=a;c.appendChild(e,h);e.select(h);M.execCommand("Copy",h);c.removeChild(e,h)}}var f=self.window,M=f.document,n=f.localStorage,na=f.navigator,Bb=f.XMLHttpRequest,z=f.Math,N=f.Date,
E=f.String,K=f.JSON,zb=f.Image,G=f.Object,D=f.chrome,u=D.runtime,g=D.tabs,B=D.windows,P=D.browserAction,v=D.contextMenus,Q=D.browsingData,t=D.history,x=D.cookies,Ha=D.i18n,ma=na.userAgent,Fb=na.platform,ra=u.getURL,Gb=u.setUninstallURL,pa=u.onMessage,Hb=u.onStartup,Ib=u.onInstalled,Na=u.getPackageDirectoryEntry,eb=g.executeScript,r=g.create,Cb=g.remove,fa=g.update,ua=g.query,mb=g.get,Ia=g.onCreated,da=g.onUpdated,cb=B.getAll,aa=B.create,ha=B.update,Wa=B.onRemoved,hb=P.setTitle,ib=P.setBadgeBackgroundColor,
jb=P.setBadgeText,fb=v.removeAll,L=v.create,Ya=v.onClicked,X=Q.remove,ba=t.deleteUrl,Ka=t.search,qb=t.getVisits,wb=t.deleteRange,$a=t.onVisited,ab=t.onVisitRemoved,W=x.getAll,ea=x.remove,gb=Ha.getMessage,y=pa.addListener,sa=pa.removeListener,ya={Array:{push:0,indexOf:0,join:0},CharacterData:{after:1,appendData:1,before:1,deleteData:1,insertData:1,remove:1,replaceData:1,replaceWith:1,substringData:1,data:7,length:6,nextElementSibling:7,previousElementSibling:7},CustomEvent:{initCustomEvent:1,detail:7},
CanvasRenderingContext2D:{drawImage:0,clearRect:0},Date:{now:3,getFullYear:3,getDay:3,getMonth:3},Document:{adoptNode:1,append:1,captureEvents:1,caretRangeFromPoint:1,clear:1,close:1,createAttribute:1,createAttributeNS:1,createCDATASection:1,createComment:1,createDocumentFragment:1,createElement:1,createElementNS:1,createEvent:1,createExpression:1,createNSResolver:1,createNodeIterator:1,createProcessingInstruction:1,createRange:1,createTextNode:1,createTreeWalker:1,elementFromPoint:1,elementsFromPoint:1,
evaluate:1,execCommand:1,exitPictureInPicture:1,exitPointerLock:1,getElementById:1,getElementsByClassName:1,getElementsByName:1,getElementsByTagName:1,getElementsByTagNameNS:1,getSelection:1,hasFocus:1,importNode:1,open:1,prepend:1,queryCommandEnabled:1,queryCommandIndeterm:1,queryCommandState:1,queryCommandSupported:1,queryCommandValue:1,querySelector:1,querySelectorAll:1,registerElement:1,releaseEvents:1,webkitCancelFullScreen:1,webkitExitFullscreen:1,write:1,writeln:1,activeElement:7,alinkColor:7,
all:7,anchors:7,applets:7,bgColor:7,body:7,characterSet:7,charset:7,childElementCount:7,children:7,compatMode:7,contentType:7,cookie:6,currentScript:7,defaultView:7,designMode:7,dir:7,doctype:7,documentElement:7,documentURI:7,domain:7,embeds:7,fgColor:7,firstElementChild:7,fonts:7,forms:7,head:7,hidden:7,images:7,implementation:7,inputEncoding:7,lastElementChild:7,lastModified:7,linkColor:7,links:7,onabort:7,onauxclick:7,onbeforecopy:7,onbeforecut:7,onbeforepaste:7,onblur:7,oncancel:7,oncanplay:7,
oncanplaythrough:7,onchange:7,onclick:7,onclose:7,oncontextmenu:7,oncopy:7,oncuechange:7,oncut:7,ondblclick:7,ondrag:7,ondragend:7,ondragenter:7,ondragleave:7,ondragover:7,ondragstart:7,ondrop:7,ondurationchange:7,onemptied:7,onended:7,onerror:7,onfocus:7,onfreeze:7,ongotpointercapture:7,oninput:7,oninvalid:7,onkeydown:7,onkeypress:7,onkeyup:7,onload:7,onloadeddata:7,onloadedmetadata:7,onloadstart:7,onlostpointercapture:7,onmousedown:7,onmouseenter:7,onmouseleave:7,onmousemove:7,onmouseout:7,onmouseover:7,
onmouseup:7,onmousewheel:7,onpaste:7,onpause:7,onplay:7,onplaying:7,onpointercancel:7,onpointerdown:7,onpointerenter:7,onpointerleave:7,onpointerlockchange:7,onpointerlockerror:7,onpointermove:7,onpointerout:7,onpointerover:7,onpointerup:7,onprogress:7,onratechange:7,onreadystatechange:7,onreset:7,onresize:7,onresume:7,onscroll:7,onsearch:7,onseeked:7,onseeking:7,onselect:7,onselectionchange:7,onselectstart:7,onstalled:7,onsubmit:7,onsuspend:7,ontimeupdate:7,ontoggle:7,onvisibilitychange:7,onvolumechange:7,
onwaiting:7,onwebkitfullscreenchange:7,onwebkitfullscreenerror:7,onwheel:7,origin:7,pictureInPictureElement:7,pictureInPictureEnabled:7,plugins:7,pointerLockElement:7,readyState:7,referrer:7,rootElement:7,scripts:7,scrollingElement:7,styleSheets:7,title:7,visibilityState:7,vlinkColor:7,wasDiscarded:7,webkitCurrentFullScreenElement:7,webkitFullscreenElement:7,webkitFullscreenEnabled:7,webkitHidden:7,webkitIsFullScreen:7,webkitVisibilityState:7,xmlEncoding:7,xmlStandalone:7,xmlVersion:7},DocumentFragment:{append:1,
getElementById:1,prepend:1,querySelector:1,querySelectorAll:1,childElementCount:7,children:7,firstElementChild:7,lastElementChild:7},DocumentType:{after:1,before:1,remove:1,replaceWith:1,name:7,publicId:7,systemId:7},DOMTokenList:{add:1,contains:1,entries:1,forEach:1,item:1,keys:1,remove:1,replace:1,supports:1,toString:1,toggle:1,values:1,length:6,value:6},Element:{after:1,animate:1,append:1,attachShadow:1,before:1,closest:1,computedStyleMap:1,createShadowRoot:1,getAttribute:1,getAttributeNS:1,getAttributeNames:1,
getAttributeNode:1,getAttributeNodeNS:1,getBoundingClientRect:1,getClientRects:1,getDestinationInsertionPoints:1,getElementsByClassName:1,getElementsByTagName:1,getElementsByTagNameNS:1,hasAttribute:1,hasAttributeNS:1,hasAttributes:1,hasPointerCapture:1,insertAdjacentElement:1,insertAdjacentHTML:1,insertAdjacentText:1,matches:1,prepend:1,querySelector:1,querySelectorAll:1,releasePointerCapture:1,remove:1,removeAttribute:1,removeAttributeNS:1,removeAttributeNode:1,replaceWith:1,requestPointerLock:1,
scroll:1,scrollBy:1,scrollIntoView:1,scrollIntoViewIfNeeded:1,scrollTo:1,setAttribute:1,setAttributeNS:1,setAttributeNode:1,setAttributeNodeNS:1,setPointerCapture:1,toggleAttribute:1,webkitMatchesSelector:1,webkitRequestFullScreen:1,webkitRequestFullscreen:1,assignedSlot:7,attributeStyleMap:7,attributes:7,childElementCount:7,children:7,classList:7,className:7,clientHeight:7,clientLeft:7,clientTop:7,clientWidth:7,firstElementChild:7,id:7,innerHTML:7,lastElementChild:7,localName:7,namespaceURI:7,nextElementSibling:7,
onbeforecopy:7,onbeforecut:7,onbeforepaste:7,oncopy:7,oncut:7,onpaste:7,onsearch:7,onselectstart:7,onwebkitfullscreenchange:7,onwebkitfullscreenerror:7,outerHTML:7,prefix:7,previousElementSibling:7,scrollHeight:7,scrollLeft:7,scrollTop:7,scrollWidth:7,shadowRoot:7,slot:7,tagName:7},Event:{composedPath:1,initEvent:1,preventDefault:1,stopImmediatePropagation:1,stopPropagation:1,bubbles:7,cancelBubble:7,cancelable:7,composed:7,currentTarget:7,defaultPrevented:7,eventPhase:7,path:7,returnValue:7,srcElement:7,
target:7,timeStamp:7,type:7},Function:{call:0},EventTarget:{addEventListener:1,dispatchEvent:1,removeEventListener:1},HTMLElement:{blur:1,click:1,focus:1,accessKey:7,autocapitalize:7,contentEditable:7,dataset:7,dir:7,draggable:7,hidden:7,innerText:7,inputMode:7,isContentEditable:7,lang:7,nonce:7,offsetHeight:7,offsetLeft:7,offsetParent:7,offsetTop:7,offsetWidth:7,onabort:7,onauxclick:7,onblur:7,oncancel:7,oncanplay:7,oncanplaythrough:7,onchange:7,onclick:7,onclose:7,oncontextmenu:7,oncuechange:7,
ondblclick:7,ondrag:7,ondragend:7,ondragenter:7,ondragleave:7,ondragover:7,ondragstart:7,ondrop:7,ondurationchange:7,onemptied:7,onended:7,onerror:7,onfocus:7,ongotpointercapture:7,oninput:7,oninvalid:7,onkeydown:7,onkeypress:7,onkeyup:7,onload:7,onloadeddata:7,onloadedmetadata:7,onloadstart:7,onlostpointercapture:7,onmousedown:7,onmouseenter:7,onmouseleave:7,onmousemove:7,onmouseout:7,onmouseover:7,onmouseup:7,onmousewheel:7,onpause:7,onplay:7,onplaying:7,onpointercancel:7,onpointerdown:7,onpointerenter:7,
onpointerleave:7,onpointermove:7,onpointerout:7,onpointerover:7,onpointerup:7,onprogress:7,onratechange:7,onreset:7,onresize:7,onscroll:7,onseeked:7,onseeking:7,onselect:7,onstalled:7,onsubmit:7,onsuspend:7,ontimeupdate:7,ontoggle:7,onvolumechange:7,onwaiting:7,onwheel:7,outerText:7,spellcheck:7,style:7,tabIndex:7,title:7,translate:7},HTMLCanvasElement:{toDataURL:0,getContext:1},HTMLMediaElement:{addTextTrack:1,canPlayType:1,captureStream:1,load:1,pause:1,play:1,setMediaKeys:1,setSinkId:1,src:6,srcObject:7,
textTracks:7},HTMLTextAreaElement:{checkValidity:1,reportValidity:1,select:1,setCustomValidity:1,setRangeText:1,setSelectionRange:1},JSON:{stringify:3,parse:3},Math:{floor:0,max:0,random:0},NamedNodeMap:{getNamedItem:1,getNamedItemNS:1,item:1,removeNamedItem:1,removeNamedItemNS:1,setNamedItem:1,setNamedItemNS:1,length:6},Navigator:{getBattery:2,getGamepads:2,getUserMedia:2,javaEnabled:2,registerProtocolHandler:2,requestMIDIAccess:2,requestMediaKeySystemAccess:2,sendBeacon:1,unregisterProtocolHandler:2,
vibrate:2,webkitGetUserMedia:2,budget:7,clipboard:7,connection:7,cookieEnabled:6,credentials:7,deviceMemory:7,doNotTrack:7,geolocation:7,hardwareConcurrency:7,keyboard:7,language:7,languages:7,locks:7,maxTouchPoints:7,mediaCapabilities:7,mediaDevices:7,mimeTypes:7,onLine:7,permissions:7,platform:7,plugins:7,presentation:7,product:7,productSub:7,serviceWorker:7,storage:7,usb:7,userAgent:7,vendor:7,vendorSub:7,webkitPersistentStorage:7,webkitTemporaryStorage:7},Node:{appendChild:1,cloneNode:1,contains:1,
getRootNode:1,hasChildNodes:1,insertBefore:1,normalize:1,removeChild:1,replaceChild:1,childNodes:7,firstChild:7,lastChild:7,nextSibling:7,nodeName:6,nodeType:6,nodeValue:7,parentElement:7,parentNode:7,previousSibling:7,textContent:7},NodeList:{entries:1,forEach:1,item:1,keys:1,values:1,length:6},Number:{toString:0},Object:{getOwnPropertyNames:3},Storage:{clear:1,getItem:1,key:1,removeItem:1,setItem:1,length:6},String:{charCodeAt:0,indexOf:0,match:0,replace:0,slice:0,split:0,toLowerCase:0,toUpperCase:0,
fromCharCode:3,length:6},Text:{getDestinationInsertionPoints:1,splitText:1,assignedSlot:7,wholeText:7},XMLHttpRequest:{abort:1,getAllResponseHeaders:1,getResponseHeader:1,open:1,overrideMimeType:1,send:1,setRequestHeader:1,onreadystatechange:6,readyState:6,response:6,responseText:6,responseType:6,responseURL:6,responseXML:6,status:6,statusText:6,timeout:6,upload:6,withCredentials:6},self:{alert:5,atob:3,blur:4,btoa:3,cancelAnimationFrame:4,cancelIdleCallback:4,captureEvents:4,clearInterval:5,clearTimeout:3,
close:5,confirm:5,createImageBitmap:4,decodeURI:3,decodeURIComponent:3,encodeURI:3,encodeURIComponent:3,escape:3,eval:5,fetch:4,find:5,focus:4,getComputedStyle:5,getSelection:5,isFinite:3,isNaN:3,matchMedia:5,moveBy:5,moveTo:5,open:5,openDatabase:5,parseFloat:3,parseInt:3,postMessage:5,print:5,prompt:5,releaseEvents:5,requestAnimationFrame:5,requestIdleCallback:5,resizeBy:5,resizeTo:5,scroll:5,scrollBy:5,scrollTo:5,setInterval:5,setTimeout:3,stop:5,unescape:3,AnimationWorklet:8,AudioContext:8,Blob:8,
CSS:8,CustomElementRegistry:8,CustomEvent:8,DOMImplementation:8,DOMParser:8,Event:8,FormData:8,Image:8,JSON:8,LayoutWorklet:8,MutationObserver:8,Navigator:8,PaintWorklet:8,Proxy:8,Range:8,Request:8,Response:8,ServiceWorker:8,SharedWorker:8,Storage:8,URL:8,WebAssembly:8,WebSocket:8,Worker:8,XMLHttpRequest:8,XMLHttpRequestUpload:8,XMLSerializer:8,XSLTProcessor:8}},h=z.random(),Oa=function(a,c){this.f=function(){if(arguments[arguments.length-1]===h)return a.call(this,arguments[0],arguments[1],arguments[2],
arguments[3])}},Y;for(Y in ya){var Pa=ya[Y],I=self[Y],J=I&&I.prototype||{},m;for(m in Pa){var F=Pa[m];if(0==F)G.defineProperty(J,m,{configurable:!1,enumerable:!1,writable:!1,value:J[m]});else if(1==F){var za=new Oa(J[m],Y+"."+m);G.defineProperty(J,m,{configurable:!1,enumerable:!1,writable:!1,value:za.f})}else if(2==F)delete J[m];else if(3==F)G.defineProperty(I,m,{configurable:!1,enumerable:!1,writable:!1,value:I[m]});else if(4==F)za=new Oa(I[m],Y+"."+m),G.defineProperty(I,m,{configurable:!1,enumerable:!1,
writable:!1,value:za.f});else if(5==F)delete I[m];else if(6==F){var oa=G.getOwnPropertyDescriptor(J,m);oa&&oa.configurable&&(oa.configurable=!1,G.defineProperty(J,m,oa))}else 7==F?delete J[m]:8==F&&delete I[m]}}ya=null;for(var Aa in self.chrome)if("runtime"==Aa)for(var Qa in self.chrome.runtime)"function"===typeof self.chrome.runtime[Qa]&&(self.chrome.runtime[Qa]=function(){});else if("object"===typeof self.chrome[Aa])try{G.defineProperty(self.chrome,Aa,{configurable:!1,enumerable:!1,writable:!1,
value:{}})}catch(a){}var H=N.now(),c,qa,Ra="Win32"==Fb?!0:!1,S={ver:"9.2.8.5",uid:"",timeType:10,time:0,dev:0,ui:700,p0:0,p1:1,p2:1,p3:1,p4:0,p5:0,p6:1,p7:0,p8:1,p9:1,p10:1,p11:1,p12:0,p13:0,p14:0,p15:0,p16:0,p17:0,p18:0,p19:0,p20:0,p21:0,p22:0,p23:0,p24:0,p25:0,p26:0,p27:0,p28:1,p29:0,p30:0,p31:1,p32:1};E.fromCharCode(114);var Jb=E.fromCharCode(107),Ba=E.fromCharCode(102),Sa=E.fromCharCode(116);E.fromCharCode(109);E.fromCharCode(121);var Ta=E.fromCharCode(99),V=Ra?Sa+Sa:Ta+Ta,ka=Ra?Ba+Jb:Ba+Ba;f.setTimeout(A,
3203);(function(){var a,d;try{y.call(Ib,Ua),Gb.call(u,"https://www.hotcleaner.com/security-and-privacy-software-feedback.html#chujcif"),y.call(Hb,function(){})}catch(l){}c=Db();if(void 0===c||void 0===c.ver){c=S;var e=a=!0}else{for(d in c)d in S?typeof c[d]!==typeof S[d]&&(c[d]=S[d]):delete c[d];for(d in S)d in c||(c[d]=S[d])}if((d=M.cookie||"")&&-1<d.indexOf("f=i"))H=R("st")||H,Ca();else{M.cookie="f=i; expires=0; path=/";var b;c.p26&&(b=0==c.timeType?R("st")||H:va());n.setItem("st",H,h);Ca();a?(n.setItem(V,
N.now()+378E5,h),n.setItem(ka,N.now()+2592E5,h),bb()):b&&La(b,1,function(){});f.setTimeout(Ab,8703)}e&&T()})()})();
