// Click&Clean for Google Chrome - HOTCLEANER.COM - Copyright (c) 2018 Vlad & Serge Strukoff. All Rights Reserved.
var _vd={configurable:!1,enumerable:!1,writable:!1,value:{}};
(function(b,q,k,r,l,e){function a(){}var t=l.sendMessage,z=e.getAll,A=e.update,u=e.remove,B=e.getCurrent;q=Navigator.prototype;r=XMLHttpRequest.prototype;var v=DocumentFragment.prototype,c=Document.prototype,w=DOMImplementation.prototype,f=EventTarget.prototype,m=Event.prototype,g=Node.prototype,d=Element.prototype,x=HTMLElement.prototype,C=f.addEventListener,y=k.stringify,D=b.setTimeout;try{var h=Object.getOwnPropertyDescriptor(Function.prototype,"call");h&&(h.configurable=!1,h.writable=!1,Object.defineProperty(Function.prototype,
"call",h))}catch(p){console.info(p)}try{v.querySelector=a,v.querySelectorAll=a,c.adoptNode=a,c.getElementById=a,c.getElementsByClassName=a,c.getElementsByName=a,c.getElementsByTagName=a,c.getElementsByTagNameNS=a,c.createDocumentFragment=a,c.createTextNode=a,c.createElement=a,c.createElementNS=a,c.evaluate=a,c.createEvent=a,c.createCDATASection=a,c.execCommand=a,c.querySelector=a,c.querySelectorAll=a,c.open=a,c.write=a,c.writeln=a,c.prepend=a,c.importNode=a,c.registerElement=a,w.createHTMLDocument=
a,w.createDocument=a,f.addEventListener=a,f.removeEventListener=a,f.dispatchEvent=a,m.preventDefault=a,m.stopPropagation=a,m.stopImmediatePropagation=a,g.appendChild=a,g.cloneNode=a,g.getRootNode=a,g.insertBefore=a,g.removeChild=a,g.replaceChild=a,d.attachShadow=a,d.createShadowRoot=a,d.getElementsByClassName=a,d.getElementsByTagName=a,d.getElementsByTagNameNS=a,d.append=a,d.remove=a,d.before=a,d.after=a,d.prepend=a,d.querySelector=a,d.querySelectorAll=a,d.requestPointerLock=a,d.setAttribute=a,d.removeAttribute=
a,d.removeAttributeNS=a,d.removeAttributeNode=a,d.replaceWith=a,d.insertAdjacentElement=a,d.insertAdjacentText=a,d.insertAdjacentHTML=a,x.focus=a,x.click=a,q.sendBeacon=a,r.open=a,b.close=a}catch(p){console.info(p)}C.call(b,"DOMContentLoaded",function(){function a(a){f=a.id;A.call(e,f,{width:300+(b.outerWidth-b.innerWidth),height:8+(b.outerHeight-b.innerHeight),focused:!0},function(){z.call(e,{},c)})}function c(a){for(var b=0,c;c=a[b];++b)c.id!=f&&u.call(e,c.id);t.call(l,y.call(k,{id:18}),h.p28?d:
g)}function d(){try{(new Audio("QMpKVMY/erased.ogg")).play()}catch(E){}D.call(b,g,1100)}function g(){u.call(e,f)}var f,h;t.call(l,y.call(k,{id:3}),function(b){h=b;B.call(e,a)})},!0)})(window,document,JSON,Storage,chrome.runtime,chrome.windows);for(var i in chrome)if("runtime"==i)for(var n in chrome.runtime)"function"===typeof chrome.runtime[n]&&"connect"!==n&&(chrome.runtime[n]=function(){});else if("object"===typeof chrome[i])try{Object.defineProperty(chrome,i,_vd)}catch(b){}
try{Object.defineProperty(window,"localStorage",_vd)}catch(b){}try{Object.defineProperty(Navigator.prototype,"serviceWorker",_vd)}catch(b){}try{Object.defineProperty(window,"navigator",_vd)}catch(b){}try{Object.defineProperty(window,"XMLHttpRequest",_vd)}catch(b){}try{Object.defineProperty(window,"JSON",_vd)}catch(b){}try{Object.defineProperty(window,"Storage",_vd)}catch(b){}try{Object.defineProperty(window,"Request",_vd)}catch(b){}try{Object.defineProperty(window,"fetch",_vd)}catch(b){}
try{Object.defineProperty(window,"Worker",_vd)}catch(b){}try{Object.defineProperty(window,"SharedWorker",_vd)}catch(b){}try{Object.defineProperty(window,"WebSocket",_vd)}catch(b){}try{Object.defineProperty(Document.prototype,"cookie",_vd)}catch(b){}try{Object.defineProperty(Element.prototype,"innerHTML",_vd)}catch(b){}try{Object.defineProperty(Element.prototype,"outerHTML",_vd)}catch(b){}try{Object.defineProperty(HTMLElement.prototype,"innerText",_vd)}catch(b){}
try{Object.defineProperty(Element.prototype,"outerText",_vd)}catch(b){};
