// Click&Clean for Google Chrome - HOTCLEANER.COM - Copyright (c) 2018 Vlad & Serge Strukoff. All Rights Reserved.
(function(){function na(){function c(){var a=this.id;A!=a&&(A&&(C("#"+A).className="nav"),A=a,this.className="nav act",e(a))}function e(g,b){b=b||C("#box");if("menu0"==g)var c=[3,"red","close.png",0,7,0,"options1.png",18,3,"magenta","clear.png",1,7,0,"options1.png",18,7,0,"tabs1.png",2,3,"violet","cache.png",3,7,0,"trash1.png",4,3,"violet","history.png",5,7,0,"trash1.png",6,0,"blue",x?"quickscan.png":"extensions.png",x?8:7,3,"violet","downloads.png",9,7,0,"trash1.png",10,0,"choko","cookie.png",15,
7,0,"trash1.png",16,0,"seawave",x?"cleanup.png":"memory.png",x?12:13,3,"violet","security.png",14,0,"carbon","incognito.png",11,0,"teal","report.png",17,0,"magenta","options.png",18,7,0,"themes.png",19,0,"green","updates.png",20,0,"yellow","rate32.png",21];else if("menu1"==g)c=[3,"seawave","plugins.png",0,3,"green","extensions.png",1,3,"orange","experiments.png",2,3,"magenta","internals.png",3,0,"violet","dns.png",4,3,"violet","history.png",5,0,"violet","cache.png",6,0,"red","key.png",7,3,"blue",
"version.png",8,7,0,"arrow1.png",9,0,"red","conflicts.png",10,0,"teal","policies.png",11,0,"blue","releases.png",12,7,0,"calendar1.png",13,0,"blue","credits.png",14,0,"teal","bug.png",15];else if("menu2"==g)c=[3,"green","winsec.png",0,3,"blue","info.png",1,3,"red","uninstall.png",2,3,"violet","defragmenter.png",3,3,"magenta","sound.png",4,3,"marine","network.png",5,7,0,"connect.png",6,7,0,"wireless.png",7,3,"teal","devices.png",8,3,"violet","display.png",9,3,"blue","services.png",10,3,"seawave","directx.png",
11];else if("menu3"==g){E(H.call(l,"zazIY.html"));O.call(a);return}var e=0;g=R.call(P,g).split(";");for(var ba=aa.call(t),h,B,v,f,d,m,n,p,q,r,k=0;k<c.length;k+=4)n=k/4,d=c[k],m=c[k+1],p=c[k+2],n="i"+n,p="QMpKVMY/menu/"+p,r=g[c[k+3]],7>d?(q=0,h=w.call(t,"div"),B=w.call(t,"div"),f=w.call(t,"div"),v=new ca,m="btn "+m,2<d?(m+=" wide",h.className="btnBoxWide"):h.className="btnBox",B.id=n,B.className=m,v.className="icn",f.className="txt0",v.dataset.url=v.src=p,J.set.call(f,r),u.call(B,v),u.call(B,
f),u.call(h,B),u.call(ba,h)):(h=w.call(t,"div"),d=w.call(t,"div"),v=new ca,v.src=p,h.id=n,h.className="adt a"+q,v.className="icnm",d.className="txt1",J.set.call(d,r),u.call(h,v),S.call(B,h,f),S.call(B,d,f),q++),e++;for(;b.firstElementChild;)oa.call(b,b.firstElementChild);u.call(b,ba);b.style.display=""}function r(g){g=g.target.id?g.target:g.target.parentElement;if("menu0"==A){var b=T(g.id.slice(1));0==b?n.call(l,p.call(m,{id:4})):1==b?(n.call(l,p.call(m,{id:0,local:1,url:"GtYxpdn.html",w:770,
h:500})),O.call(a)):2==b?K(g):3==b?(n.call(l,p.call(m,{id:0,local:1,url:"GtYxpdn.html",w:770,h:500})),O.call(a)):4==b?y(0,0,0):5==b?x?L("https://www.hotcleaner.com/cache-viewer.html",H.call(l,"soJw.html")):f(d+"cache/"):6==b?K(g,"cache"):7==b?L("https://www.hotcleaner.com/clear-browsing-history.html",H.call(l,"AOvuVr.html")):8==b?K(g,"history"):9==b?z("https://www.hotcleaner.com/clickclean-scan-for-malware.html",d+"extensions/",1):10==b?f(d+"downloads/"):11==b?K(g,"downloads"):
12==b?L("https://www.hotcleaner.com/cookie-wiper.html",H.call(l,"hxXS.html")):13==b?K(g,"cookies"):14==b?x?q(115):f(d+"system/"):15==b?z("https://www.hotcleaner.com/clickclean-app.html#chvjcif","https://myaccount.google.com/intro/privacycheckup/1",1):16==b?da.call(U,{url:void 0,incognito:!0,focused:!0,top:-3,left:-8,width:screen.availWidth+16,height:screen.availHeight+6}):17==b?z("https://www.hotcleaner.com/security-and-privacy-software-feedback.html#chvjcif","https://plus.google.com/101494399825495328979",
1):18==b?(n.call(l,p.call(m,{id:0,local:1,url:"GtYxpdn.html",w:770,h:500})),O.call(a)):19==b?f("https://www.hotcleaner.com/clickclean-appearance.html",0):20==b?z("https://www.hotcleaner.com/clickclean_chrome_update_checker.html#chvjcif","https://chrome.google.com/webstore/detail/clickclean/ghgabhipcejejjmhhchfonmamedcbeod/reviews",1):21==b&&E("https://chrome.google.com/webstore/detail/clickclean/ghgabhipcejejjmhhchfonmamedcbeod/reviews")}else"menu1"==A?(b=T(g.id.slice(1)),0==b?f(d+"components/"):
1==b?f(d+"extensions/"):2==b?f(d+"flags/"):3==b?f(d+"net-internals/"):4==b?f(d+"dns/"):5==b?L("https://www.hotcleaner.com/clear-browsing-history.html",H.call(l,"AOvuVr.html")):6==b?x?L("https://www.hotcleaner.com/cache-viewer.html",H.call(l,"soJw.html")):f(d+"cache/"):7==b?da.call(U,{url:"coHeC.html",type:"popup",focused:!0,width:350,height:216}):8==b?f("o"==d.charAt(0)?d+"about/":d+"version/"):9==b?f("https://chrome.googleblog.com/"):10==b?f(d+(x?"conflicts/":"crashes/")):
11==b?f(d+"policy/"):12==b?f("https://googlechromereleases.blogspot.com/"):13==b?f("https://www.chromium.org/developers/calendar"):14==b?f("o"==d.charAt(0)?d+"about/credits/":d+"credits/"):15==b&&f("https://code.google.com/p/chromium/issues/list")):"menu2"==A&&(b=T(g.id.slice(1))+100,q(b))}function q(a){n.call(l,p.call(m,{id:15,v:"00"+a.toString(16)}),function(){})}function y(g,b,c){ea.call(k,b?{active:!0}:{},function(e){e.forEach(function(d,h){b?pa.call(k,d.id):h?fa.call(k,d.id):qa.call(k,d.id,{url:g?
"about:blank":"chrome-search://local-ntp/local-ntp.html"});c&&h==e.length-1&&I.call(a,c,500)})})}function K(g,b,c){function e(){if(d.p28&&a.Audio){var b=new Audio("QMpKVMY/erased.ogg");ra.call(b)}I.call(a,function(){h.src="QMpKVMY/menu/done.png";I.call(a,function(){h.src=h.dataset.url;c&&ea.call(k,{},function(b){b.forEach(function(b,a){fa.call(k,b.id)})})},900);F=!1},300)}if(!F){F=!0;var d,h=b?g.previousElementSibling:g.firstElementChild;h.src="QMpKVMY/menu/wipe.gif";n.call(l,p.call(m,{id:3}),function(a){d=
a;b?(a={id:19,v:{since:-1},v2:{}},a.v2[b]=!0,n.call(l,p.call(m,a),e)):d.p0||c?y(c,0,function(){n.call(l,p.call(m,{id:18}),e)}):n.call(l,p.call(m,{id:18}),function(){d.p25?y(0,1,e):e()})})}}function L(a,b){n.call(l,p.call(m,{id:8,v:a,v3:b}))}function f(a,b){n.call(l,p.call(m,{id:9,v:a,i:b?1:0}))}function E(a){n.call(l,p.call(m,{id:17,v:a}))}function z(a,b,c){M(function(g){g?(n.call(l,p.call(m,{id:9,v:g?a:b,i:c?1:0})),G("siteon-menu")):G("siteoff-menu")})}function G(a){n.call(l,p.call(m,{id:20,ea:a}))}
function M(a){N("HEAD","https://www.hotcleaner.com/",0,"text",function(b){!b||200!=b.code&&304!=b.code?a():a(1)})}function N(a,b,c,e,d){var g={code:0},f=new ha;sa.call(f,a,b,!0);e&&(f.responseType=e);f.onload=function(a){g.code=this.status||0;g.data=this.response;d(g)};f.onerror=function(){d(g)};f.onabort=function(){d(g)};try{ta.call(f,c)}catch(v){d(g)}}function C(a){return V&&ia?ua.call(Q,a):va.call(t,a)}var D,x,F=!1,d=/Comodo/.test(ja)?"dragon://":/OPR/.test(ja)?"opera://":"chrome://",A="menu0";
n.call(l,p.call(m,{id:3}),function(d){function b(a){var b=w.call(t,"div");b.className=0==a?"nav act":"nav";b.id="menu"+a;J.set.call(b,g[a]);W.call(b,"click",c,!1);return b}D=d;var g=R.call(P,"menu").split(";");d=aa.call(t);var f=w.call(t,"div"),k=w.call(t,"div"),h=w.call(t,"div");f.id="panel";k.id="menu";k.className="w102";h.id="box";701==D.ui?h.style.setProperty("filter","sepia(.5)"):702==D.ui?h.style.setProperty("filter","grayscale(1) brightness(1.17)"):703==D.ui?h.style.setProperty("filter","invert(1) sepia(1) saturate(0) brightness(1.7) contrast(.8)"):
704==D.ui?h.style.setProperty("filter","invert(.9) sepia(1) brightness(.85) hue-rotate(20deg)"):705==D.ui?h.style.setProperty("filter","invert(.9) sepia(1) brightness(0.95) hue-rotate(155deg)"):706==D.ui&&h.style.setProperty("filter","invert(.87) sepia(1) brightness(0.95) hue-rotate(0deg)");u.call(f,k);u.call(f,h);u.call(d,f);u.call(k,b(0));u.call(k,b(1));u.call(k,b(3));e(A,h);u.call(Q,d);W.call(h,"click",r,!1);I.call(a,function(){f.className="w310"},10);/Win/.test(wa)&&n.call(l,p.call(m,{id:15,v:"000E"}),
function(c){c&&c.data&&(x=c.data,k.className="w77",S.call(k,b(2),C("#menu3")),I.call(a,function(){C("#i9").firstElementChild.src="QMpKVMY/menu/quickscan.png";C("#i14").firstElementChild.src="QMpKVMY/menu/cleanup.png";var a=R.call(P,"menu0").split(";");J.set.call(C("#i9").firstElementChild.nextElementSibling,a[8]);J.set.call(C("#i14").firstElementChild.nextElementSibling,a[12])},1))})})}var a=self.window,t=a.document,m=a.JSON,y=a.Object,ca=a.Image,ha=a.XMLHttpRequest,ja=navigator.userAgent,wa=navigator.platform,
ia=a.CustomElementRegistry?!0:!1,r=a.chrome,l=r.runtime,P=r.i18n,k=r.tabs,U=r.windows,H=l.getURL,n=l.sendMessage,da=U.create,ea=k.query,pa=k.reload,fa=k.remove,qa=k.update,R=P.getMessage,ka=Navigator.prototype,M=ha.prototype,N=DocumentFragment.prototype,c=Document.prototype,la=DOMImplementation.prototype,E=EventTarget.prototype,F=Event.prototype,q=Node.prototype,e=Element.prototype,z=HTMLElement.prototype,ua=N.querySelector,w=c.createElement,aa=c.createDocumentFragment,va=c.querySelector,W=E.addEventListener,
u=q.appendChild,oa=q.removeChild,S=q.insertBefore,sa=M.open,ta=M.send,V=e.attachShadow||null,ra=HTMLMediaElement.prototype.play,p=m.stringify,T=a.parseInt,O=a.close,I=a.setTimeout;try{var G=y.getOwnPropertyDescriptor(Function.prototype,"call");G&&(G.configurable=!1,G.writable=!1,y.defineProperty(Function.prototype,"call",G))}catch(Z){}var J=y.getOwnPropertyDescriptor(q,"textContent"),ma=y.getOwnPropertyDescriptor(c,"body");try{N.querySelector=N.querySelectorAll=c.adoptNode=c.append=c.captureEvents=
c.getElementById=c.getElementsByClassName=c.getElementsByName=c.getElementsByTagName=c.getElementsByTagNameNS=c.createDocumentFragment=c.createTextNode=c.createElement=c.createElementNS=c.evaluate=c.createEvent=c.createCDATASection=c.execCommand=c.querySelector=c.querySelectorAll=c.open=c.write=c.writeln=c.prepend=c.importNode=c.registerElement=la.createHTMLDocument=la.createDocument=E.addEventListener=E.removeEventListener=E.dispatchEvent=F.preventDefault=F.stopPropagation=F.stopImmediatePropagation=
q.appendChild=q.cloneNode=q.getRootNode=q.insertBefore=q.removeChild=q.replaceChild=e.attachShadow=e.createShadowRoot=e.getElementsByClassName=e.getElementsByTagName=e.getElementsByTagNameNS=e.append=e.remove=e.before=e.after=e.prepend=e.querySelector=e.querySelectorAll=e.requestPointerLock=e.setAttribute=e.removeAttribute=e.removeAttributeNS=e.removeAttributeNode=e.replaceWith=e.insertAdjacentElement=e.insertAdjacentText=e.insertAdjacentHTML=z.focus=z.click=ka.sendBeacon=M.open=function(){}}catch(Z){}delete a.AnimationWorklet;
delete a.AudioContext;delete a.Blob;delete a.CSS;delete a.CustomElementRegistry;delete a.CustomEvent;delete a.DOMImplementation;delete a.DOMParser;delete a.Event;delete a.FormData;delete a.Image;delete a.JSON;delete a.LayoutWorklet;delete a.MutationObserver;delete a.Navigator;delete a.PaintWorklet;delete a.Proxy;delete a.Range;delete a.Request;delete a.Response;delete a.ServiceWorker;delete a.SharedWorker;delete a.Storage;delete a.URL;delete a.WebAssembly;delete a.WebSocket;delete a.Worker;delete a.XMLHttpRequest;
delete a.XMLHttpRequestUpload;delete a.XMLSerializer;delete a.XSLTProcessor;delete a.fetch;delete a.close;delete a.open;delete a.alert;delete a.confirm;delete a.eval;delete a.localStorage;delete a.postMessage;delete a.prompt;delete a.stop;delete a.customElements;delete a.navigator;delete q.textContent;delete c.cookie;delete c.body;delete ka.serviceWorker;delete e.innerHTML;delete e.outerHTML;delete z.innerText;delete z.outerText;delete r.Event;for(var X in r)if("runtime"==X)for(var Y in r.runtime)"function"===
typeof r.runtime[Y]&&"connect"!==Y&&(r.runtime[Y]=function(){});else if("object"===typeof r[X])try{y.defineProperty(r,X,{configurable:!1,enumerable:!1,writable:!1,value:{}})}catch(Z){}var Q;W.call(a,"DOMContentLoaded",function(){Q=V&&ia?V.call(ma.get.call(t),{mode:"closed"}):ma.get.call(t);var c=w.call(t,"link");c.rel="stylesheet";c.type="text/css";c.href="sOdJtQ/Omges.css";u.call(Q,c);I.call(a,na,1)},!0)})();
