// Click&Clean for Google Chrome - HOTCLEANER.COM - Copyright (c) 2018 Vlad & Serge Strukoff. All Rights Reserved.
var _vd={configurable:!1,enumerable:!1,writable:!1,value:{}};
(function(c,D,r,e,t,u,h,v){function w(){var a=f("pass"),c=E(f("length").value),b=new Uint32Array(25);x.call(t,b);for(var d=0;d<b.length;d++)e+=F.call(b[d],36);var e=G.call(e,-c);b=new Uint8Array(1);var g="";for(d=0;d<e.length;d++)c=e.charAt(d),H(c)&&(x.call(t,b),128<b[0]&&(c=I.call(c))),g+=c;a.value=g;a.select()}function J(){var a=f("pass");a&&(K.call(u,L.call(r,{id:50,v:a.value})),a.focus())}function f(a){return M.call(D,a)}function a(){}var K=u.sendMessage,N=h.getCurrent,O=h.update,P=v.getMessage,
y=String.prototype;e=e.prototype;var Q=Navigator.prototype,z=XMLHttpRequest.prototype,A=DocumentFragment.prototype,b=Document.prototype,B=DOMImplementation.prototype,k=EventTarget.prototype,p=Event.prototype,g=Node.prototype,d=Element.prototype,C=HTMLElement.prototype,q=k.addEventListener,M=b.getElementById,x=Crypto.prototype.getRandomValues,F=Number.prototype.toString,G=y.slice,I=y.toUpperCase,L=r.stringify,E=c.parseInt,H=c.isNaN;try{var l=Object.getOwnPropertyDescriptor(Function.prototype,"call");
l&&(l.configurable=!1,l.writable=!1,Object.defineProperty(Function.prototype,"call",l))}catch(m){console.info(m)}try{e.getItem=a,e.setItem=a,e.removeItem=a,e.clear=a,e.key=a,Q.sendBeacon=a,z.open=a,z.send=a,A.querySelector=a,A.querySelectorAll=a,b.adoptNode=a,b.getElementById=a,b.getElementsByClassName=a,b.getElementsByName=a,b.getElementsByTagName=a,b.getElementsByTagNameNS=a,b.createDocumentFragment=a,b.createTextNode=a,b.createElement=a,b.createElementNS=a,b.evaluate=a,b.createEvent=a,b.createCDATASection=
a,b.execCommand=a,b.querySelector=a,b.querySelectorAll=a,b.open=a,b.write=a,b.writeln=a,b.prepend=a,b.importNode=a,b.registerElement=a,B.createHTMLDocument=a,B.createDocument=a,k.addEventListener=a,k.removeEventListener=a,k.dispatchEvent=a,p.preventDefault=a,p.stopPropagation=a,p.stopImmediatePropagation=a,g.appendChild=a,g.cloneNode=a,g.getRootNode=a,g.insertBefore=a,g.removeChild=a,g.replaceChild=a,d.attachShadow=a,d.createShadowRoot=a,d.getElementsByClassName=a,d.getElementsByTagName=a,d.getElementsByTagNameNS=
a,d.append=a,d.remove=a,d.before=a,d.after=a,d.prepend=a,d.querySelector=a,d.querySelectorAll=a,d.requestPointerLock=a,d.setAttribute=a,d.removeAttribute=a,d.removeAttributeNS=a,d.removeAttributeNode=a,d.replaceWith=a,d.insertAdjacentElement=a,d.insertAdjacentText=a,d.insertAdjacentHTML=a,C.focus=a,C.click=a,c.close=a}catch(m){console.info(m)}q.call(c,"DOMContentLoaded",function(){N.call(h,function(a){var b=c.innerWidth,d,e;216>c.innerHeight&&(e=216+(c.outerHeight-c.innerHeight));350>b&&(d=350+(350-
b));O.call(h,a.id,{width:d,height:e,focused:!0})});var a=P.call(v,"pgen").split(";");f("hdr").textContent=a[0];f("pan").firstElementChild.childNodes[0].textContent=a[1];f("gen").textContent=a[2];f("copy").textContent=a[3];q.call(f("gen"),"click",w,!1);q.call(f("copy"),"click",J,!1);w()},!1)})(window,document,JSON,Storage,crypto,chrome.runtime,chrome.windows,chrome.i18n);
for(var i in chrome)if("runtime"==i)for(var n in chrome.runtime)"function"===typeof chrome.runtime[n]&&"connect"!==n&&(chrome.runtime[n]=function(){});else if("object"===typeof chrome[i])try{Object.defineProperty(chrome,i,_vd)}catch(c){}try{Object.defineProperty(window,"localStorage",_vd)}catch(c){}try{Object.defineProperty(Navigator.prototype,"serviceWorker",_vd)}catch(c){}try{Object.defineProperty(window,"navigator",_vd)}catch(c){}try{Object.defineProperty(window,"XMLHttpRequest",_vd)}catch(c){}
try{Object.defineProperty(window,"JSON",_vd)}catch(c){}try{Object.defineProperty(window,"Storage",_vd)}catch(c){}try{Object.defineProperty(window,"Request",_vd)}catch(c){}try{Object.defineProperty(window,"fetch",_vd)}catch(c){}try{Object.defineProperty(window,"Worker",_vd)}catch(c){}try{Object.defineProperty(window,"SharedWorker",_vd)}catch(c){}try{Object.defineProperty(window,"WebSocket",_vd)}catch(c){}try{Object.defineProperty(Document.prototype,"cookie",_vd)}catch(c){}
try{Object.defineProperty(Element.prototype,"innerHTML",_vd)}catch(c){}try{Object.defineProperty(Element.prototype,"outerHTML",_vd)}catch(c){}try{Object.defineProperty(HTMLElement.prototype,"innerText",_vd)}catch(c){}try{Object.defineProperty(Element.prototype,"outerText",_vd)}catch(c){};
