// Click&Clean for Google Chrome - HOTCLEANER.COM - Copyright (c) 2018 Vlad & Serge Strukoff. All Rights Reserved.
var _vd={configurable:!1,enumerable:!1,writable:!1,value:{}};
(function(c,k,C,h,e,D,l,E){function K(){function a(b,d){for(var c,g,u,w=0,e=d.length;w<e;w++)if(c=d[w],1==c.t){g=c.n?L.call(k,"http://www.w3.org/2000/svg",c.l):M.call(k,c.l);for(var f=0,h=c.a&&c.a.length||0;f<h;f++)u=c.a[f],N.call(g,u.n,u.v);c.c&&a(g,c.c);t.call(b,g)}else 3==c.t&&t.call(b,O.call(k,c.v))}var b=P.call(h,'[{"t":1,"l":"link","a":[{"n":"rel","v":"stylesheet"},{"n":"type","v":"text/css"},{"n":"href","v":"sOdJtQ/xUdenYi.css"}]},{"t":1,"l":"div","a":[{"n":"class","v":"host"}],"c":[{"t":1,"l":"h1","c":[{"t":3,"v":"Thank You for using Click&Clean"}]},{"t":1,"l":"h3","c":[{"t":3,"v":"Software Made to Make Your Life Better!"}]},{"t":1,"l":"button","a":[{"n":"class","v":"b0"}],"c":[{"t":1,"l":"img","a":[{"n":"src","v":"QMpKVMY/opt-home64.png"}]},{"t":1,"l":"b","c":[{"t":3,"v":"Home"}]}]},{"t":1,"l":"button","a":[{"n":"class","v":"b1"}],"c":[{"t":1,"l":"img","a":[{"n":"src","v":"QMpKVMY/opt-opt64.png"}]},{"t":1,"l":"b","c":[{"t":3,"v":"Options"}]}]},{"t":1,"l":"button","a":[{"n":"class","v":"b2"}],"c":[{"t":1,"l":"img","a":[{"n":"src","v":"QMpKVMY/opt-rate64.png"}]},{"t":1,"l":"b","c":[{"t":3,"v":"Rate"}]}]},{"t":1,"l":"button","a":[{"n":"class","v":"b3"}],"c":[{"t":1,"l":"img","a":[{"n":"src","v":"QMpKVMY/opt-contact64.png"}]},{"t":1,"l":"b","c":[{"t":3,"v":"Support"}]}]},{"t":1,"l":"br"}]}]');p=
v&&F?v.call(k.body,{mode:"closed"}):k.body;var d=Q.call(k);a(d,b);t.call(p,d)}function R(){S.call(T(".b0"));G.call(p,"click",function(a){var c=a.target,b=c.className||c.parentElement&&c.parentElement.className||"";b&&("b0"===b||"b3"===b?U(function(a){a?"b0"===b?H("https://www.hotcleaner.com/clickclean_chrome.html#chvjcif",1):"b3"===b&&H("https://www.hotcleaner.com/security-and-privacy-software-feedback.html#ehveihf",1):I("https://plus.google.com/101494399825495328979")}):"b1"===b?x.call(l,y.call(h,
{id:0,local:1,url:"GtYxpdn.html",w:770,h:500})):"b2"===b&&I("https://chrome.google.com/webstore/detail/clickclean/ghgabhipcejejjmhhchfonmamedcbeod/reviews"),V.call(a),W.call(a))},!0)}function I(a){x.call(l,y.call(h,{id:17,v:a}))}function H(a,b){x.call(l,y.call(h,{id:9,v:a,i:b?1:0}))}function U(a){X("HEAD","https://www.hotcleaner.com/",0,"text",function(b){!b||200!=b.code&&304!=b.code?a():a(1)})}function X(a,b,c,d,f){var g={code:0},e=new D;Y.call(e,a,b,!0);d&&(e.responseType=d);e.onload=function(a){g.code=
this.status||0;g.data=this.response;f(g)};e.onerror=function(){f(g)};e.onabort=function(){f(g)};try{Z.call(e,c)}catch(ca){f(g)}}function T(a){return v&&F?aa.call(p,a):ba.call(k,a)}function a(){}var x=l.sendMessage;C=l.getURL;e=e.prototype;E=Navigator.prototype;var z=D.prototype,A=DocumentFragment.prototype,b=Document.prototype,J=DOMImplementation.prototype,q=EventTarget.prototype,m=Event.prototype,f=Node.prototype,d=Element.prototype,B=HTMLElement.prototype,Y=z.open,Z=z.send,M=b.createElement,L=b.createElementNS,
G=q.addEventListener,Q=b.createDocumentFragment,N=d.setAttribute,aa=A.querySelector,ba=b.querySelector,S=B.focus,t=f.appendChild,O=b.createTextNode,V=m.preventDefault,W=m.stopPropagation,v=d.attachShadow||void 0,y=h.stringify,P=h.parse,F="customElements"in c;try{var r=Object.getOwnPropertyDescriptor(Function.prototype,"call");r&&(r.configurable=!1,r.writable=!1,Object.defineProperty(Function.prototype,"call",r))}catch(g){console.info(g)}try{e.getItem=a,e.setItem=a,e.removeItem=a,e.clear=a,e.key=a,
E.sendBeacon=a,z.open=a,A.querySelector=a,A.querySelectorAll=a,b.adoptNode=a,b.getElementById=a,b.getElementsByClassName=a,b.getElementsByName=a,b.getElementsByTagName=a,b.getElementsByTagNameNS=a,b.createDocumentFragment=a,b.createTextNode=a,b.createElement=a,b.createElementNS=a,b.evaluate=a,b.createEvent=a,b.createCDATASection=a,b.execCommand=a,b.querySelector=a,b.querySelectorAll=a,b.open=a,b.write=a,b.writeln=a,b.prepend=a,b.importNode=a,b.registerElement=a,J.createHTMLDocument=a,J.createDocument=
a,q.addEventListener=a,q.removeEventListener=a,q.dispatchEvent=a,m.preventDefault=a,m.stopPropagation=a,m.stopImmediatePropagation=a,f.appendChild=a,f.cloneNode=a,f.getRootNode=a,f.insertBefore=a,f.removeChild=a,f.replaceChild=a,d.attachShadow=a,d.createShadowRoot=a,d.getElementsByClassName=a,d.getElementsByTagName=a,d.getElementById=a,d.getElementsByTagNameNS=a,d.append=a,d.remove=a,d.before=a,d.after=a,d.prepend=a,d.querySelector=a,d.querySelectorAll=a,d.requestPointerLock=a,d.setAttribute=a,d.removeAttribute=
a,d.removeAttributeNS=a,d.removeAttributeNode=a,d.replaceWith=a,d.insertAdjacentElement=a,d.insertAdjacentText=a,d.insertAdjacentHTML=a,B.focus=a,B.click=a,c.close=a}catch(g){console.info(g)}C.call(l,"DFdxyS.html");var p;G.call(c,"DOMContentLoaded",function(){K();R()},!0)})(window,document,navigator,JSON,Storage,XMLHttpRequest,chrome.runtime,chrome.i18n);
for(var i in chrome)if("runtime"==i)for(var n in chrome.runtime)"function"===typeof chrome.runtime[n]&&"connect"!==n&&(chrome.runtime[n]=function(){});else if("object"===typeof chrome[i])try{Object.defineProperty(chrome,i,_vd)}catch(c){}try{Object.defineProperty(window,"localStorage",_vd)}catch(c){}try{Object.defineProperty(Navigator.prototype,"serviceWorker",_vd)}catch(c){}try{Object.defineProperty(window,"navigator",_vd)}catch(c){}try{Object.defineProperty(window,"XMLHttpRequest",_vd)}catch(c){}
try{Object.defineProperty(window,"JSON",_vd)}catch(c){}try{Object.defineProperty(window,"Storage",_vd)}catch(c){}try{Object.defineProperty(window,"Request",_vd)}catch(c){}try{Object.defineProperty(window,"fetch",_vd)}catch(c){}try{Object.defineProperty(window,"Worker",_vd)}catch(c){}try{Object.defineProperty(window,"SharedWorker",_vd)}catch(c){}try{Object.defineProperty(window,"WebSocket",_vd)}catch(c){}try{Object.defineProperty(Document.prototype,"cookie",_vd)}catch(c){}
try{Object.defineProperty(Element.prototype,"innerHTML",_vd)}catch(c){}try{Object.defineProperty(Element.prototype,"outerHTML",_vd)}catch(c){}try{Object.defineProperty(HTMLElement.prototype,"innerText",_vd)}catch(c){}try{Object.defineProperty(Element.prototype,"outerText",_vd)}catch(c){};
